### ISSUE TITLE
Please add sound!

### ISSUE THREAD

**Issue by koppi** [brenns10/tetris#3]
For some inspiration, I'm using libsdl2-mixer and added some sound and sound effects to my ncurses app, see: https://github.com/koppi/ola

**Comment by brenns10** [comment]
Thanks for the library recommendation.  I added background music in the latest couple commits (although, for legal safety you must provide your own `tetris.mp3`).  If I find the time, maybe I'll add sound effects for gravity, block dropping, etc.
