### ISSUE TITLE
unable to initialize SDL_mixer

### ISSUE THREAD

**Issue by congdv** [brenns10/tetris#5]
Hi, I got a error when run your program.

> unable to initialize SDL_mixer
> 3

My os is ubuntu 16.04 64 bit

**Comment by jeon3029** [comment]
I have same problem.

**Comment by jeon3029** [comment]
I solved the problem by install
sdl2 and sdl2_mixer
I hope this help!

**Comment by ur4ltz** [comment]
I solved the problem by
>make SDL=no

**Comment by pixelcmtd** [comment]
same problem, disabling SDL solved it for me

**Comment by sahilgajjar** [comment]
same problem, but where do i disable SDL ?

**Comment by ur4ltz** [comment]
> same problem, but where do i disable SDL ?

Yes.

**Comment by a1e5Term** [comment]
does not work. if I do:
`make SDL=no`
then I get:
`cc obj/release/util.o obj/release/main.o obj/release/tetris.o -Wall -pedantic -lncurses -o bin/release/main
/usr/bin/ld: obj/release/main.o: in function `boss_mode':
/home/user/tetris/src/main.c:103: undefined reference to `Mix_PauseMusic'
/usr/bin/ld: /home/user/tetris/src/main.c:128: undefined reference to `Mix_ResumeMusic'
/usr/bin/ld: obj/release/main.o: in function `main':
/home/user/tetris/src/main.c:205: undefined reference to `SDL_Init'
/usr/bin/ld: /home/user/tetris/src/main.c:209: undefined reference to `Mix_Init'
/usr/bin/ld: /home/user/tetris/src/main.c:213: undefined reference to `Mix_OpenAudio'
/usr/bin/ld: /home/user/tetris/src/main.c:217: undefined reference to `Mix_AllocateChannels'
/usr/bin/ld: /home/user/tetris/src/main.c:218: undefined reference to `Mix_LoadMUS'
/usr/bin/ld: /home/user/tetris/src/main.c:220: undefined reference to `Mix_PlayMusic'
/usr/bin/ld: /home/user/tetris/src/main.c:301: undefined reference to `Mix_HaltMusic'
/usr/bin/ld: /home/user/tetris/src/main.c:302: undefined reference to `Mix_FreeMusic'
/usr/bin/ld: /home/user/tetris/src/main.c:303: undefined reference to `Mix_CloseAudio'
/usr/bin/ld: /home/user/tetris/src/main.c:304: undefined reference to `Mix_Quit'
collect2: error: ld returned 1 exit status
make: *** [Makefile:81: bin/release/main] Error 1`

please help

**Comment by brenns10** [comment]
Run `make clean` and then `make SDL=no`
